- name: Docker is installed
  hosts: web
  become: yes
  tasks:

    - name: Install packages
      apt:
        pkg:
          - docker.io
          - python3-pip
          - mariadb-server
          - pkg-config
          - libmariadb-dev
          - apt-transport-https
          - ca-certificates
          - software-properties-common
          - virtualenv
        state: present

    - name: install mysqlclient
      raw: pip install --break-system-packages mariadb mysqlclient

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu jammy stable
        state: present

    - name: Update apt and install docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: true
