- name: setup Mysql with medium_db db and remote login
  become: yes
  hosts: web
  tasks:

    - name: start and enable mysql service
      service:
        name: mysql
        state: started
        enabled: yes

    - name: creating wordpress database
      mysql_db:
        name: "wordpress"
        state: present

    - name: allow non localhost connections
      ini_file:
        dest: /etc/mysql/my.cnf
        section: mysqld
        option: "{{ item.option }}"
        value: "{{ item.value }}"
      register: my_cnf_changes
      with_items:
        - { option: bind-address, value: "*" }

    - name: creating mysql user
      mysql_user:
        name: "wordpress"
        password: "wordpress"
        priv: 'wordpress.*:ALL'
        host: '%'
        column_case_sensitive: true
        state: present

    - name: restart mysql if cnf changed
      command: service mysql restart
      when: my_cnf_changes

  handlers:
    - name: Restart mysql
      service:
        name: mysql
        state: restarted
