---
- name: docker is installed
  hosts: all
  become: yes

  tasks:

    - name: Check Docker version
      command: docker --version
      register: docker_version
      ignore_errors: true

    - name: Install Docker
      apt:
        name: docker.io
        state: present
      when: docker_version.rc != 0
