- name: Prometheus is installed
  become: yes
  hosts: monitor
  tasks:

    - name: mkdir /etc/prometheus
      file:
        path: /etc/prometheus
        state: directory

    - name: Copy prometheus conf
      copy:
        src: ./conf/prometheus.yml
        dest: /etc/prometheus/prometheus.yml

    - name: Install Prometheus
      apt:
        name: prometheus
        state: latest
        update_cache: yes

- name: node_exporter on web nodes
  hosts: web
  become: yes
  roles:
    - role: prometheus.prometheus.node_exporter
