- name: Docker is installed
  hosts: web
  become: yes
  tasks:

    - name: Install Docker
      apt:
        pkg:
          - docker.io
          - python3-pip
        state: present

- name: Run Wordpress in Docker
  hosts: web
  become: yes

  tasks:

    - name: Copy WordPress compose file
      copy:
        src: ./wordpress.yml
        dest: /var/www/docker-compose.yml

    - name: docker compose deploy WordPress
      community.docker.docker_compose:
        project_src: /var/www
