
- name: mkdir /etc/prometheus
  file:
    path: /etc/prometheus
    state: directory

- name: Copy prometheus conf
  become: yes
  copy:
    src: ./roles/monitor/files/prometheus.yml
    dest: /etc/prometheus/prometheus.yml

- name: Install Prometheus
  become: yes
  apt:
    name: prometheus
    state: latest
    update_cache: yes
