version: '3.9'

services:

  web:
    image: wordpress:6.4.1
    environment:
      WORDPRESS_DB_HOST: host.docker.internal
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html # instead of s3
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.rehorek.rule=Host(`web.local`)"
        - "traefik.http.routers.rehorek.entrypoints=web"
