
- name: Install packages
  become: yes
  apt:
    pkg:
      - docker.io
      - python3-pip
      - mariadb-server
      - pkg-config
      - libmariadb-dev
      - apt-transport-https
      - ca-certificates
      - software-properties-common
      - virtualenv
      - unzip
    state: present

- name: install mysqlclient
  raw: pip install --break-system-packages mariadb mysqlclient
