version: '3.9'

services:

  web:
    image: wordpress:6.4.1
    environment:
      WORDPRESS_DB_HOST: host.docker.internal # amazon rds
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    volumes:
      - ./src:/var/www/html # s3 location
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.rehorek.rule=Host(`web.local`)"
        - "traefik.http.routers.rehorek.entrypoints=web,websecure"

  traefik:
    image: traefik:v2.10
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--entryPoints.websecure.address=:443"
      - "--entryPoints.web.address=:8"
      - "--entryPoints.websecure.http.tls=true"
    ports:
      - "80:80" # http
      - "443:443" # https
      - "8080:8080" # dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
